### ISSUE TITLE
simplest installation & usage

### ISSUE THREAD

**Issue by hugurp** [internet4000/dashboard-organisation#1]
# environment variable
The goal is to make the installation, and usage, of `dashboard-organisation` extremely simple.

Maybe the `organisation` variable can saved in an `environment var`, so each user willing to install the software would have to just change that part of the software to make it run and use it.

Everyone therefore be able to pull changes from the main repo, with no merge conflict (if no change was done).

# one click deploy
Maybe some one click deploy buttons, to `netlify`, `now`, `surge` etc. could be inserted in the readme, to ease setup.

**Comment by oskarrough** [comment]
If we refactor to an environment variable we can deploy with now.sh directly from github like this:

`now internet4000/dashboard-organisation -e org="lego"`

**Comment by hugurp** [comment]
closed by #6
