### ISSUE TITLE
Deployment to now.sh

### ISSUE THREAD

**Issue by oskarrough** [internet4000/dashboard-organisation#19]
With a small modification to the package.json we can support deployments on now.sh, which also makes it easy to set ENV vars. Examples:

- `now internet4000/dashboard-organisation -e REACT_APP_USER=oskarrough`
- `now internet4000/dashboard-organisation -e REACT_APP_ORGANISATION=internet4000`

Can also put it in readme. See https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment

**Comment by hugurp** [comment]
nice!
